# Generated by Django 4.0.3 on 2023-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributed_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner (0-2 years)'), ('intermediate', 'Intermediate (2-5 years)'), ('advanced', 'Advanced (5+ years)')], max_length=20)),
                ('architectural_complexity', models.BooleanField(default=False)),
                ('software_performance', models.BooleanField(default=False)),
                ('software_scalability', models.BooleanField(default=False)),
                ('compatibility', models.BooleanField(default=False)),
                ('budget_constraint', models.BooleanField(default=False)),
                ('schedule_constraint', models.BooleanField(default=False)),
                ('scope_constraint', models.BooleanField(default=False)),
                ('resource_constraint', models.BooleanField(default=False)),
                ('market_change', models.BooleanField(default=False)),
                ('competition', models.BooleanField(default=False)),
                ('regulatory_requirements', models.BooleanField(default=False)),
                ('skill_gaps', models.BooleanField(default=False)),
                ('turnover', models.BooleanField(default=False)),
                ('team_communication_issues', models.BooleanField(default=False)),
            ],
        ),
    ]
