# Generated by Django 4.0.3 on 2023-07-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0002_riskassessmentdata_delete_contributed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCalculatorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('architectural_complexity', models.CharField(max_length=3)),
                ('software_performance', models.CharField(max_length=3)),
                ('software_scalability', models.CharField(max_length=3)),
                ('compatibility', models.CharField(max_length=3)),
                ('budget_constraint', models.CharField(max_length=3)),
                ('schedule_constraint', models.CharField(max_length=3)),
                ('scope_constraint', models.CharField(max_length=3)),
                ('resource_constraint', models.CharField(max_length=3)),
                ('market_change', models.CharField(max_length=3)),
                ('competition', models.CharField(max_length=3)),
                ('regulatory_requirements', models.CharField(max_length=3)),
                ('skill_gaps', models.CharField(max_length=3)),
                ('turnover', models.CharField(max_length=3)),
                ('team_communication_issues', models.CharField(max_length=3)),
                ('output', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='riskassessmentdata',
            options={},
        ),
    ]
