# Generated by Django 4.0.3 on 2023-07-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0003_riskcalculatorhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskcalculatorhistory',
            old_name='output',
            new_name='predicted_output',
        ),
    ]
